apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  API_HOST: {{ .Values.config.apiHost | quote }}
  API_PORT: {{ .Values.config.apiPort | quote }}
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  DEBUG: {{ .Values.config.debug | quote }}
  MAX_CONCURRENT_SCRAPERS: {{ .Values.config.maxConcurrentScrapers | quote }}
  SCRAPER_TIMEOUT: {{ .Values.config.scraperTimeout | quote }}
  POSTGRESQL_USER: {{ .Values.database.user | quote }}
  POSTGRESQL_HOST: {{ .Values.database.host | quote }}
  POSTGRESQL_PORT: {{ .Values.database.port | quote }}
  POSTGRESQL_DB_NAME: {{ .Values.database.name | quote }}
